version: 0.1
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --prod
    post_build:
         commands:
            - aws s3 sync --delete dist/Project-Two s3://project2client
artifacts:
    files:
        - '**/*'
    base-directory: 'project2client*'
    discard-paths: yes
